#!/usr/bin/env python3

import os
from pprint import pprint
import requests
import sys

def main():
    contest_id = sys.argv[1]
    python_problem_link = "https://raw.githubusercontent.com/joseph-hlucny/codeforces/main/python-resources/problem.py"
    codeforces_req = requests.get(f"https://codeforces.com/api/contest.standings?contestId={contest_id}")
    contest = codeforces_req.json()["result"]["problems"]
    os.mkdir(f"{contest_id}")
    
    for problem in contest:
        problem_dir = f"{contest_id}/{problem['index']}"
        problem_path = f"{problem_dir}/{problem['index']}.py"
        os.mkdir(problem_dir)
        with open(problem_path, "w") as problem_file:
            problem_req = requests.get(python_problem_link)
            problem_file.write(problem_req.text)



if __name__ == "__main__":
    main()